export default [
  {
    name: "de",
    flag: "de",
    des: "Deutsch",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "en",
    flag: "gb",
    des: "English",
    hideInLandingPages: false,
    availableIn: ["*"],
  },
  {
    name: "es",
    flag: "es",
    des: "Español",
    hideInLandingPages: false,
    availableIn: ["*"],
  },
  {
    name: "ms",
    flag: "my",
    des: "Malay",
    hideInLandingPages: false,
    availableIn: ["*"],
  },
  {
    name: "pt",
    flag: "pt",
    des: "Português",
    hideInLandingPages: false,
    availableIn: ["*"],
  },
  {
    name: "ar",
    flag: "sa",
    des: "العربية",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "cz",
    flag: "cz",
    des: "Česky",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "fr",
    flag: "fr",
    des: "Français",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "hi",
    flag: "in",
    des: "ɦɪndi",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "id",
    flag: "id",
    des: "Indonesia",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "it",
    flag: "it",
    des: "Italiano",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "hu",
    flag: "hu",
    des: "Magyar",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "pl",
    flag: "pl",
    des: "Polski",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "th",
    flag: "th",
    des: "ภาษาไทย",
    hideInLandingPages: false,
    availableIn: ["*"],
  },
  {
    name: "vi",
    flag: "vn",
    des: "Tiếng Việt",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "zh-hans",
    flag: "cn",
    des: "中文",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "zh-tw",
    flag: "tw",
    des: "中文繁體",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "tr",
    flag: "tr",
    des: "Turkish",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "nl",
    flag: "nl",
    des: "Nederlands",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "el",
    flag: "gr",
    des: "Ελληνικά",
    hideInLandingPages: true,
    availableIn: ["/blog", "/article/[slug]", "/blog/education/[page]"],
  },
];
export const dataThaiFlags = [
  {
    name: "en",
    flag: "gb",
    des: "English",
    hideInLandingPages: false,
    availableIn: ["*"],
  },
  {
    name: "th",
    flag: "th",
    des: "ภาษาไทย",
    hideInLandingPages: false,
    availableIn: ["*"],
  },
];
export const dataNoMalasia = [
  {
    name: "de",
    flag: "de",
    des: "Deutsch",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "en",
    flag: "gb",
    des: "English",
    hideInLandingPages: false,
    availableIn: ["*"],
  },
  {
    name: "es",
    flag: "es",
    des: "Español",
    hideInLandingPages: false,
    availableIn: ["*"],
  },
  {
    name: "pt",
    flag: "pt",
    des: "Português",
    hideInLandingPages: false,
    availableIn: ["*"],
  },
  {
    name: "ar",
    flag: "sa",
    des: "العربية",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "cz",
    flag: "cz",
    des: "Česky",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "fr",
    flag: "fr",
    des: "Français",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "hi",
    flag: "in",
    des: "ɦɪndi",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "id",
    flag: "id",
    des: "Indonesia",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "it",
    flag: "it",
    des: "Italiano",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "hu",
    flag: "hu",
    des: "Magyar",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "pl",
    flag: "pl",
    des: "Polski",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "th",
    flag: "th",
    des: "ภาษาไทย",
    hideInLandingPages: false,
    availableIn: ["*"],
  },
  {
    name: "vi",
    flag: "vn",
    des: "Tiếng Việt",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "zh-hans",
    flag: "cn",
    des: "中文",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "zh-tw",
    flag: "tw",
    des: "中文繁體",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "tr",
    flag: "tr",
    des: "Turkish",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "nl",
    flag: "nl",
    des: "Nederlands",
    hideInLandingPages: true,
    availableIn: ["*"],
  },
  {
    name: "el",
    flag: "gr",
    des: "Ελληνικά",
    hideInLandingPages: true,
    availableIn: ["/blog", "/article/[slug]", "/blog/education/[page]"],
  },
];
